<script lang="ts">
	import { page } from '$app/stores';
	import { onMount } from 'svelte';
	import { goto } from '$app/navigation';
	import { browser } from '$app/environment';
	import { projectStore } from '$lib/stores/project-store';
	import { canvasStore } from '$lib/stores/canvas-store';
	import type { Project } from '$lib/stores/project-store';
	import { SQLDialect } from '$lib/constants';
	import LoadingScreen from '$lib/components/LoadingScreen.svelte';

	let projectId = $state('');
	let project: Project | null = null;
	let projectName = $state('');
	let selectedDialect = $state<SQLDialect>(SQLDialect.PostgreSQL);
	let generatedSQL = $state('');
	let copied = $state(false);
	let isLoading = $state(true);

	onMount(() => {
		projectId = $page.params.id || '';
		if (projectId) {
			loadProject();
		} else {
			goto('/projects');
		}
	});

	// Regenerate SQL when dialect changes
	$effect(() => {
		if (project && selectedDialect) {
			generateSQL();
		}
	});

	function loadProject() {
		isLoading = true;
		try {
			const allProjects = projectStore.getAllProjects();
			project = allProjects.find((p) => p.id === projectId) || null;

			if (project) {
				projectName = project.name;
				canvasStore.loadState(project.canvasState);
				generateSQL();
				// Delay to ensure everything is loaded
				setTimeout(() => {
					isLoading = false;
				}, 150);
			} else {
				// Project not found, redirect to projects page
				isLoading = false;
				goto('/projects');
			}
		} catch (error) {
			console.error('Failed to load project:', error);
			isLoading = false;
			goto('/projects');
		}
	}

	function generateSQL() {
		// TODO: Convert canvas state to Information Schema and generate SQL
		// For now, generate a placeholder based on nodes/edges
		const nodes = Array.from($canvasStore.nodes.values());
		const edges = Array.from($canvasStore.edges.values());

		if (!nodes || nodes.length === 0) {
			generatedSQL = '-- No entities or fact types found in the project.';
			return;
		}

		let sql = `-- ============================================================\n`;
		sql += `-- Generated by MathGraph - Visual Information Modeling Tool\n`;
		sql += `-- https://mathgraph.kablan.nl\n`;
		sql += `-- Created by Luuk Kablan\n`;
		sql += `-- ============================================================\n`;
		sql += `--\n`;
		sql += `-- Project: ${projectName}\n`;
		sql += `-- Dialect: ${selectedDialect}\n`;
		sql += `-- Generated: ${new Date().toISOString()}\n`;
		sql += `--\n`;
		sql += `-- ============================================================\n\n`;

		// Generate CREATE TABLE statements for entities
		const entities = nodes.filter((n) => n.type === 'entity');
		for (const entity of entities) {
			sql += `CREATE TABLE ${entity.label.replace(/\s+/g, '_')} (\n`;
			sql += `  id SERIAL PRIMARY KEY,\n`;
			sql += `  name VARCHAR(255) NOT NULL,\n`;
			sql += `  created_at TIMESTAMP DEFAULT CURRENT_TIMESTAMP\n`;
			sql += `);\n\n`;
		}

		// Generate relationship tables for fact types
		const factTypes = nodes.filter((n) => n.type === 'factType');
		for (const factType of factTypes) {
			const relatedEdges = edges.filter(
				(e) => e.sourceNodeId === factType.id || e.targetNodeId === factType.id
			);

			if (relatedEdges.length >= 2) {
				sql += `CREATE TABLE ${factType.label.replace(/\s+/g, '_')} (\n`;
				sql += `  id SERIAL PRIMARY KEY,\n`;

				relatedEdges.forEach((edge) => {
					const targetNode =
						$canvasStore.nodes.get(edge.targetNodeId) || $canvasStore.nodes.get(edge.sourceNodeId);
					if (targetNode && targetNode.type === 'entity') {
						sql += `  ${targetNode.label.replace(/\s+/g, '_').toLowerCase()}_id INTEGER,\n`;
					}
				});

				sql += `  created_at TIMESTAMP DEFAULT CURRENT_TIMESTAMP\n`;
				sql += `);\n\n`;
			}
		}

		generatedSQL = sql;

		// Apply syntax highlighting
		if (browser && (window as any).Prism) {
			setTimeout(() => (window as any).Prism.highlightAll(), 10);
		}
	}

	function copyToClipboard() {
		navigator.clipboard.writeText(generatedSQL);
		copied = true;
		setTimeout(() => {
			copied = false;
		}, 2000);
	}

	function downloadSQL() {
		const blob = new Blob([generatedSQL], { type: 'text/plain' });
		const url = URL.createObjectURL(blob);
		const a = document.createElement('a');
		a.href = url;
		a.download = `${projectName.replace(/\s+/g, '_')}_schema.sql`;
		a.click();
		URL.revokeObjectURL(url);
	}
</script>

<LoadingScreen {isLoading} />

<div class="export-page">
	<div class="header">
		<a href="/projects" class="back-btn"> ← Projects </a>
		<h1>🗄️ Export SQL Schema</h1>
		<div class="project-info">
			<span class="project-name">{projectName}</span>
		</div>
	</div>

	<div class="content">
		<div class="sidebar">
			<div class="section">
				<h3>Schema Overview</h3>
				<div class="stats">
					<div class="stat">
						<span class="label">Entities:</span>
						<span class="value"
							>{Array.from($canvasStore.nodes.values()).filter((n) => n.type === 'entity')
								.length}</span
						>
					</div>
					<div class="stat">
						<span class="label">Fact Types:</span>
						<span class="value"
							>{Array.from($canvasStore.nodes.values()).filter((n) => n.type === 'factType')
								.length}</span
						>
					</div>
					<div class="stat">
						<span class="label">Edges:</span>
						<span class="value">{$canvasStore.edges.size}</span>
					</div>
					<div class="stat">
						<span class="label">Constraints:</span>
						<span class="value">{$canvasStore.constraints.size}</span>
					</div>
				</div>
			</div>

			<div class="section">
				<h3>SQL Dialect</h3>
				<select bind:value={selectedDialect} class="dialect-select">
					<option value={SQLDialect.PostgreSQL}>PostgreSQL</option>
					<option value={SQLDialect.MySQL}>MySQL</option>
					<option value={SQLDialect.SQLite}>SQLite</option>
					<option value={SQLDialect.SQLServer}>SQL Server</option>
				</select>
			</div>

			<div class="section">
				<h3>Export Actions</h3>
				<button class="action-btn primary" onclick={downloadSQL}>
					<span class="icon">⬇</span>
					Download SQL
				</button>
				<button class="action-btn" onclick={copyToClipboard}>
					<span class="icon">{copied ? '✓' : '📋'}</span>
					{copied ? 'Copied!' : 'Copy to Clipboard'}
				</button>
			</div>
		</div>

		<div class="main">
			<div class="sql-preview">
				<div class="preview-header">
					<h3>Generated SQL</h3>
					<span class="dialect-badge">{selectedDialect}</span>
				</div>
				<pre class="sql-code"><code class="language-sql">{generatedSQL}</code></pre>
			</div>
		</div>
	</div>
</div>

<style>
	.export-page {
		display: flex;
		flex-direction: column;
		height: 100vh;
		background: var(--bg-primary);
	}

	.header {
		display: flex;
		align-items: center;
		gap: 1.5rem;
		padding: 1.5rem 2rem;
		background: var(--bg-secondary);
		border-bottom: 1px solid var(--border-color);
	}

	.back-btn {
		padding: 0.5rem 1rem;
		background: transparent;
		border: 1px solid var(--border-color);
		border-radius: 6px;
		color: var(--text-secondary);
		cursor: pointer;
		font-size: 0.875rem;
		transition: all 0.2s;
		text-decoration: none;
		display: inline-flex;
		align-items: center;
	}

	.back-btn:hover {
		background: var(--bg-primary);
		color: var(--text-primary);
	}

	h1 {
		font-size: 1.5rem;
		font-weight: 600;
		color: var(--text-primary);
		margin: 0;
	}

	.project-info {
		margin-left: auto;
	}

	.project-name {
		font-size: 0.875rem;
		color: var(--text-secondary);
		padding: 0.5rem 1rem;
		background: var(--bg-primary);
		border-radius: 6px;
	}

	.content {
		display: grid;
		grid-template-columns: 300px 1fr;
		flex: 1;
		overflow: hidden;
	}

	.sidebar {
		background: var(--bg-secondary);
		border-right: 1px solid var(--border-color);
		padding: 2rem;
		overflow-y: auto;
		display: flex;
		flex-direction: column;
		gap: 2rem;
	}

	.section h3 {
		font-size: 0.875rem;
		font-weight: 600;
		color: var(--text-secondary);
		text-transform: uppercase;
		letter-spacing: 0.05em;
		margin: 0 0 1rem 0;
	}

	.stats {
		display: flex;
		flex-direction: column;
		gap: 0.75rem;
	}

	.stat {
		display: flex;
		justify-content: space-between;
		align-items: center;
		padding: 0.5rem;
		background: var(--bg-primary);
		border-radius: 4px;
	}

	.stat .label {
		font-size: 0.875rem;
		color: var(--text-secondary);
	}

	.stat .value {
		font-weight: 600;
		color: var(--text-primary);
	}

	.dialect-select {
		width: 100%;
		padding: 0.75rem;
		background: var(--bg-primary);
		border: 1px solid var(--border-color);
		border-radius: 6px;
		color: var(--text-primary);
		font-size: 0.875rem;
		cursor: pointer;
	}

	.dialect-select:focus {
		outline: none;
		border-color: var(--accent-primary);
	}

	.action-btn {
		width: 100%;
		padding: 0.75rem 1rem;
		background: var(--bg-primary);
		border: 1px solid var(--border-color);
		border-radius: 6px;
		color: var(--text-primary);
		font-size: 0.875rem;
		font-weight: 500;
		cursor: pointer;
		display: flex;
		align-items: center;
		justify-content: center;
		gap: 0.5rem;
		transition: all 0.2s;
		margin-bottom: 0.5rem;
	}

	.action-btn:hover {
		background: var(--hover-bg);
	}

	.action-btn.primary {
		background: var(--accent-primary);
		color: white;
		border-color: var(--accent-primary);
	}

	.action-btn.primary:hover {
		opacity: 0.9;
	}

	.icon {
		font-size: 1rem;
	}

	.main {
		padding: 2rem;
		overflow-y: auto;
	}

	.sql-preview {
		background: var(--bg-secondary);
		border: 1px solid var(--border-color);
		border-radius: 8px;
		overflow: hidden;
	}

	.preview-header {
		display: flex;
		justify-content: space-between;
		align-items: center;
		padding: 1rem 1.5rem;
		background: var(--bg-primary);
		border-bottom: 1px solid var(--border-color);
	}

	.preview-header h3 {
		font-size: 1rem;
		font-weight: 600;
		color: var(--text-primary);
		margin: 0;
	}

	.dialect-badge {
		padding: 0.25rem 0.75rem;
		background: var(--accent-primary);
		color: white;
		border-radius: 4px;
		font-size: 0.75rem;
		font-weight: 600;
	}

	.sql-code {
		margin: 0;
		padding: 1.5rem;
		background: #1e1e1e;
		color: #d4d4d4;
		font-family: 'Consolas', 'Monaco', 'Courier New', monospace;
		font-size: 0.875rem;
		line-height: 1.6;
		overflow-x: auto;
		min-height: 400px;
	}

	.sql-code code {
		color: #d4d4d4;
	}

	@media (max-width: 768px) {
		.content {
			grid-template-columns: 1fr;
		}

		.sidebar {
			border-right: none;
			border-bottom: 1px solid var(--border-color);
		}
	}
</style>
