<script lang="ts">
	import { page } from '$app/stores';
	import { onMount, untrack } from 'svelte';
	import { goto } from '$app/navigation';
	import { browser } from '$app/environment';
	import { projectStore } from '$lib/stores/project-store';
	import { canvasStore } from '$lib/stores/canvas-store';
	import type { Project } from '$lib/stores/project-store';
	import type { SQLTable } from '$lib/types';
	import { SQLDialect } from '$lib/constants';
	import { SQLGenerator } from '$lib/sql-generator';
	import { SchemaConverter } from '$lib/schema-converter';
	import LoadingScreen from '$lib/components/LoadingScreen.svelte';

	let projectId = $state('');
	let project: Project | null = null;
	let projectName = $state('');
	let selectedDialect = $state<SQLDialect>(SQLDialect.PostgreSQL);
	let generatedSQL = $state('');
	let copied = $state(false);
	let isLoading = $state(true);
	let isGenerating = $state(false);
	let sqlKey = $state(0); // Key to force re-render
	let lastDialect = $state<SQLDialect | null>(null); // Track last dialect to prevent loops

	// Schema statistics
	let schemaStats = $state({
		entities: 0,
		factTypes: 0,
		edges: 0,
		constraints: 0,
		tables: 0,
		relationships: 0
	});

	onMount(() => {
		projectId = $page.params.id || '';
		if (projectId) {
			loadProject();
		} else {
			goto('/projects');
		}
	});

	// Regenerate SQL when dialect changes
	$effect(() => {
		// Track the dialect as a primitive value to ensure reactivity
		const currentDialect = selectedDialect;

		// Only regenerate if dialect actually changed and project is loaded
		if (untrack(() => project !== null && currentDialect !== lastDialect)) {
			lastDialect = currentDialect;
			generateSQL();
		}
	});

	function loadProject() {
		isLoading = true;
		try {
			const allProjects = projectStore.getAllProjects();
			project = allProjects.find((p) => p.id === projectId) || null;

			if (project) {
				projectName = project.name;
				canvasStore.loadState(project.canvasState);
				lastDialect = selectedDialect; // Initialize lastDialect
				generateSQL();
				// Delay to ensure everything is loaded
				setTimeout(() => {
					isLoading = false;
				}, 150);
			} else {
				// Project not found, redirect to projects page
				isLoading = false;
				goto('/projects');
			}
		} catch (error) {
			console.error('Failed to load project:', error);
			isLoading = false;
			goto('/projects');
		}
	}

	function generateSQL() {
		isGenerating = true;
		sqlKey++; // Force re-render of the code block
		generatedSQL = '-- Generating SQL schema...\n';
		// Use setTimeout to allow UI to update before heavy computation
		setTimeout(() => {
			try {
				// Convert canvas state to Information Schema
				const informationSchema = SchemaConverter.convertToInformationSchema(
					$canvasStore,
					projectName
				);

				// Generate SQL using the proper SQL generator
				const generator = new SQLGenerator(selectedDialect);
				const sqlSchema = generator.generateSchema(informationSchema);
				const ddl = generator.generateDDL(sqlSchema);

				// Update statistics
				schemaStats = {
					entities: informationSchema.entities.size,
					factTypes: informationSchema.factTypes.size,
					edges: $canvasStore.edges.size,
					constraints: $canvasStore.constraints.size,
					tables: sqlSchema.tables.length,
					relationships: sqlSchema.tables.reduce(
						(count: number, table: SQLTable) => count + table.foreignKeys.length,
						0
					)
				};

				// Add header comments
				let sql = `-- ============================================================\n`;
				sql += `-- Generated by MathGraph - Visual Information Modeling Tool\n`;
				sql += `-- https://mathgraph.kablan.nl\n`;
				sql += `-- Created by Luuk Kablan\n`;
				sql += `-- ============================================================\n`;
				sql += `--\n`;
				sql += `-- Project: ${projectName}\n`;
				sql += `-- Dialect: ${selectedDialect}\n`;
				sql += `-- Generated: ${new Date().toISOString()}\n`;
				sql += `--\n`;
				sql += `-- This schema was generated from an Information Schema model\n`;
				sql += `-- using formal information systems theory.\n`;
				sql += `--\n`;
				sql += `-- Mapping Rules Applied:\n`;
				sql += `-- - Entities/Objectified Facts → Tables\n`;
				sql += `-- - Uniqueness Constraints     → PRIMARY KEY / UNIQUE\n`;
				sql += `-- - Total Role Constraints     → NOT NULL\n`;
				sql += `-- - Specialization             → Foreign Keys\n`;
				sql += `-- - Unary Facts                → Boolean Columns\n`;
				sql += `-- - Enumerations               → CHECK Constraints\n`;
				sql += `-- - Many-to-Many               → Junction Tables\n`;
				sql += `--\n`;
				sql += `-- ============================================================\n\n`;

				if (ddl.trim()) {
					sql += ddl;
				} else {
					sql += '-- No schema elements found to generate SQL.\n';
					sql += '-- Add entities and fact types to your model.\n';
				}

				generatedSQL = sql;

				// Apply syntax highlighting
				if (browser && (window as any).Prism) {
					setTimeout(() => (window as any).Prism.highlightAll(), 10);
				}
			} catch (error) {
				console.error('SQL generation error:', error);
				generatedSQL = `-- Error generating SQL: ${error instanceof Error ? error.message : 'Unknown error'}\n`;
				generatedSQL += `-- Please ensure your model is valid and try again.\n`;
			} finally {
				isGenerating = false;
			}
		}, 0);
	}

	function copyToClipboard() {
		navigator.clipboard.writeText(generatedSQL);
		copied = true;
		setTimeout(() => {
			copied = false;
		}, 2000);
	}

	function downloadSQL() {
		const blob = new Blob([generatedSQL], { type: 'text/plain' });
		const url = URL.createObjectURL(blob);
		const a = document.createElement('a');
		a.href = url;
		a.download = `${projectName.replace(/\s+/g, '_')}_schema.sql`;
		a.click();
		URL.revokeObjectURL(url);
	}
</script>

<LoadingScreen {isLoading} />

<div class="export-page">
	<div class="header">
		<a href="/projects" class="back-btn"> ← Projects </a>
		<h1>🗄️ Export SQL Schema</h1>
		<div class="project-info">
			<span class="project-name">{projectName}</span>
		</div>
	</div>

	<div class="content">
		<div class="sidebar">
			<div class="section">
				<h3>Schema Overview</h3>
				<div class="stats">
					<div class="stat">
						<span class="label">Entities:</span>
						<span class="value">{schemaStats.entities}</span>
					</div>
					<div class="stat">
						<span class="label">Fact Types:</span>
						<span class="value">{schemaStats.factTypes}</span>
					</div>
					<div class="stat">
						<span class="label">Edges:</span>
						<span class="value">{schemaStats.edges}</span>
					</div>
					<div class="stat">
						<span class="label">Constraints:</span>
						<span class="value">{schemaStats.constraints}</span>
					</div>
					<div class="stat">
						<span class="label">SQL Tables:</span>
						<span class="value">{schemaStats.tables}</span>
					</div>
					<div class="stat">
						<span class="label">Relationships:</span>
						<span class="value">{schemaStats.relationships}</span>
					</div>
				</div>
			</div>

			<div class="section">
				<h3>SQL Dialect</h3>
				<select bind:value={selectedDialect} class="dialect-select">
					<option value={SQLDialect.PostgreSQL}>PostgreSQL</option>
					<option value={SQLDialect.MySQL}>MySQL</option>
					<option value={SQLDialect.SQLite}>SQLite</option>
					<option value={SQLDialect.SQLServer}>SQL Server</option>
				</select>
			</div>

			<div class="section">
				<h3>Export Actions</h3>
				<button class="action-btn primary" onclick={downloadSQL}>
					<span class="icon">⬇</span>
					Download SQL
				</button>
				<button class="action-btn" onclick={copyToClipboard}>
					<span class="icon">{copied ? '✓' : '📋'}</span>
					{copied ? 'Copied!' : 'Copy to Clipboard'}
				</button>
			</div>
		</div>

		<div class="main">
			<div class="sql-preview">
				<div class="preview-header">
					<h3>Generated SQL</h3>
					<span class="dialect-badge">
						{selectedDialect}
						{#if isGenerating}
							<span class="generating">⟳</span>
						{/if}
					</span>
				</div>
				{#key sqlKey}
					<pre class="sql-code"><code class="language-sql">{generatedSQL}</code></pre>
				{/key}
			</div>
		</div>
	</div>
</div>

<style>
	.export-page {
		display: flex;
		flex-direction: column;
		height: 100vh;
		background: var(--bg-primary);
	}

	.header {
		display: flex;
		align-items: center;
		gap: 1.5rem;
		padding: 1.5rem 2rem;
		background: var(--bg-secondary);
		border-bottom: 1px solid var(--border-color);
	}

	.back-btn {
		padding: 0.5rem 1rem;
		background: transparent;
		border: 1px solid var(--border-color);
		border-radius: 6px;
		color: var(--text-secondary);
		cursor: pointer;
		font-size: 0.875rem;
		transition: all 0.2s;
		text-decoration: none;
		display: inline-flex;
		align-items: center;
	}

	.back-btn:hover {
		background: var(--bg-primary);
		color: var(--text-primary);
	}

	h1 {
		font-size: 1.5rem;
		font-weight: 600;
		color: var(--text-primary);
		margin: 0;
	}

	.project-info {
		margin-left: auto;
	}

	.project-name {
		font-size: 0.875rem;
		color: var(--text-secondary);
		padding: 0.5rem 1rem;
		background: var(--bg-primary);
		border-radius: 6px;
	}

	.content {
		display: grid;
		grid-template-columns: 300px 1fr;
		flex: 1;
		overflow: hidden;
	}

	.sidebar {
		background: var(--bg-secondary);
		border-right: 1px solid var(--border-color);
		padding: 2rem;
		overflow-y: auto;
		display: flex;
		flex-direction: column;
		gap: 2rem;
	}

	.section h3 {
		font-size: 0.875rem;
		font-weight: 600;
		color: var(--text-secondary);
		text-transform: uppercase;
		letter-spacing: 0.05em;
		margin: 0 0 1rem 0;
	}

	.stats {
		display: flex;
		flex-direction: column;
		gap: 0.75rem;
	}

	.stat {
		display: flex;
		justify-content: space-between;
		align-items: center;
		padding: 0.5rem;
		background: var(--bg-primary);
		border-radius: 4px;
	}

	.stat .label {
		font-size: 0.875rem;
		color: var(--text-secondary);
	}

	.stat .value {
		font-weight: 600;
		color: var(--text-primary);
	}

	.dialect-select {
		width: 100%;
		padding: 0.75rem;
		background: var(--bg-primary);
		border: 1px solid var(--border-color);
		border-radius: 6px;
		color: var(--text-primary);
		font-size: 0.875rem;
		cursor: pointer;
	}

	.dialect-select:focus {
		outline: none;
		border-color: var(--accent-primary);
	}

	.action-btn {
		width: 100%;
		padding: 0.75rem 1rem;
		background: var(--bg-primary);
		border: 1px solid var(--border-color);
		border-radius: 6px;
		color: var(--text-primary);
		font-size: 0.875rem;
		font-weight: 500;
		cursor: pointer;
		display: flex;
		align-items: center;
		justify-content: center;
		gap: 0.5rem;
		transition: all 0.2s;
		margin-bottom: 0.5rem;
	}

	.action-btn:hover {
		background: var(--hover-bg);
	}

	.action-btn.primary {
		background: var(--accent-primary);
		color: white;
		border-color: var(--accent-primary);
	}

	.action-btn.primary:hover {
		opacity: 0.9;
	}

	.icon {
		font-size: 1rem;
	}

	.main {
		padding: 2rem;
		overflow-y: auto;
	}

	.sql-preview {
		background: var(--bg-secondary);
		border: 1px solid var(--border-color);
		border-radius: 8px;
		overflow: hidden;
	}

	.preview-header {
		display: flex;
		justify-content: space-between;
		align-items: center;
		padding: 1rem 1.5rem;
		background: var(--bg-primary);
		border-bottom: 1px solid var(--border-color);
	}

	.preview-header h3 {
		font-size: 1rem;
		font-weight: 600;
		color: var(--text-primary);
		margin: 0;
	}

	.dialect-badge {
		padding: 0.25rem 0.75rem;
		background: var(--accent-primary);
		color: white;
		border-radius: 4px;
		font-size: 0.75rem;
		font-weight: 600;
		display: flex;
		align-items: center;
		gap: 0.25rem;
	}

	.generating {
		display: inline-block;
		animation: spin 1s linear infinite;
	}

	@keyframes spin {
		from {
			transform: rotate(0deg);
		}
		to {
			transform: rotate(360deg);
		}
	}

	.sql-code {
		margin: 0;
		padding: 1.5rem;
		background: #1e1e1e;
		color: #d4d4d4;
		font-family: 'Consolas', 'Monaco', 'Courier New', monospace;
		font-size: 0.875rem;
		line-height: 1.6;
		overflow-x: auto;
		min-height: 400px;
	}

	.sql-code code {
		color: #d4d4d4;
	}

	@media (max-width: 768px) {
		.content {
			grid-template-columns: 1fr;
		}

		.sidebar {
			border-right: none;
			border-bottom: 1px solid var(--border-color);
		}
	}
</style>
